### ISSUE TITLE
Does not work with Typescript(ts-node-dev)

### ISSUE THREAD

**Issue by schulmacher** [kevlened/threadwork#1]
While running typescript in watch mode with `ts-node-dev`, following exception is thrown.
```
TypeError [ERR_WORKER_UNSUPPORTED_EXTENSION]: The worker script extension must be ".js", ".mjs", or ".cjs". Received ".ts"
    at new Worker (internal/worker.js:139:15)
    at new ThreadPool (/home/ace/p/api/node_modules/threadwork/index.js:81:19)
    at Object.<anonymous> (/home/ace/p/api/src/queues/x/worker.ts:9:16) <--------- my file
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/home/ace/p/api/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-5180304694670224.js:57:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5180304694670224.js:59:20)
    at Object.nodeDevHook [as .ts] (/home/ace/p/api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
[ERROR] 13:35:29 TypeError: The worker script extension must be ".js", ".mjs", or ".cjs". Received ".ts"
```
Current fix is not use typescript for the worker file.
Also it works when compiled, because then the extension is `.js`.

I think there is no proper solution for this :smile:

**Comment by kevlened** [comment]
Thanks for filing! Presumably, `ts-node-dev` just compiles each file (including your worker) when it changes and node just runs this compiled version. I wonder if compiling ts changes the way `__filename` works (that’s how I determine the worker’s location). I’ll have to take a look.

**Comment by schulmacher** [comment]
> I wonder if compiling ts changes the way __filename works

If it's compiled then the `__filename` has the `.js` extension, when running with ts-node the extension is `.ts`.

**Comment by kevlened** [comment]
I found [a related thread](https://github.com/facebook/jest/issues/10568) on jest. They have a similar model to `ts-node` that keeps compiled assets in memory. `worker_threads` requires a file to read, so files must be compiled and written to disk.

`ts-node-dev` _does_ output to a cache directory though. If you configure that directory (using `cache-directory`) and provide it to `threadwork`, I may be able to resolve to the corresponding js files.

**Comment by kevlened** [comment]
See the README for how to configure `ts-node-dev` compatibility: https://github.com/kevlened/threadwork#ts-node-dev
